### ISSUE TITLE
Problem with lookup option

### ISSUE THREAD

**Issue by codeout** [yasuhiro-ohara-ntt/bgpdump2#2]
While bff0f4dfce67cbe3d426c11d9126ed03d7955b54 fixed a crash bug according to the commit message, it introduced other problem preventing us from doing `bdpdump2 -l`.

``` zsh
bgpdump2 $ ./src/bgpdump2 rib.20150319.0000.bz2 -p 19 -l 8.8.8.8
looking up an address: 8.8.8.8
8.8.8.8: no route found.
```

When I replace `#if 0` directive with `#if 1` here, the option works:
https://github.com/yasuhiro-ohara-ntt/bgpdump2/blob/master/src/bgpdump_data.c#L442

``` zsh
bgpdump2 $ ./src/bgpdump2 rib.20150319.0000.bz2 -p 19 -l 8.8.8.8
looking up an address: 8.8.8.8
8.8.8.0/24 129.250.0.11 origin_as: 15169 as-path[2]: 2914 15169
```

Is there any chance to revert the code around there?

**Comment by codeout** [comment]
Sorry, this is not related to bff0f4d but probably f20e5334.

**Comment by yasuhironet** [comment]
Hi, thanks for testing.

It shoul be fixed now, by eca35ad8367d.

As a bonus, now it supports multiple peers at a time for lookup.

% ./src/bgpdump2 ../routeviews/rib.20150319.0000.bz2 -p 10 -p 12 -p 19 -l 8.8.8.8
looking up an address: 8.8.8.8
peer 10:
8.8.8.8: no route found.
peer 12:
8.8.8.0/24 85.114.0.217 origin_as: 15169 as-path[2]: 8492 15169
peer 19:
8.8.8.0/24 129.250.0.11 origin_as: 15169 as-path[2]: 2914 15169

Best regards,
Yasu

**Comment by codeout** [comment]
Thanks Yasu. It works :tada:

> As a bonus, now it supports multiple peers at a time for lookup.

That's also great, however I'd think that we still have to take care of when no `-p` option given.
No `-p` rather sounds like "whole ptree" to me, instead of "none of peer-based ptree".
https://github.com/yasuhiro-ohara-ntt/bgpdump2/compare/master...codeout:lookup-option

**Comment by yasuhironet** [comment]
Closing the issue.
